"""generated relationships between tables

Revision ID: 110d72d0dd48
Revises: 5f8bb5454119
Create Date: 2023-03-29 12:01:59.903087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110d72d0dd48'
down_revision = '5f8bb5454119'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
