"""generated relationships between tables

Revision ID: 42536e3ead1a
Revises: 110d72d0dd48
Create Date: 2023-03-29 12:56:57.042418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42536e3ead1a'
down_revision = '110d72d0dd48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
