"""removed suffer_score from activities table

Revision ID: 5329e0838dc9
Revises: cf58dd0bc878
Create Date: 2023-03-28 16:49:11.952240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5329e0838dc9'
down_revision = 'cf58dd0bc878'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'suffer_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('suffer_score', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
