"""added strava_id for activities table

Revision ID: cf58dd0bc878
Revises: 4683a6359bf3
Create Date: 2023-03-28 15:46:35.391570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf58dd0bc878'
down_revision = '4683a6359bf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('strava_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'strava_id')
    # ### end Alembic commands ###
